[package]
name = "rosu-pp-js"
version = "1.0.0"
edition = "2021"
authors = ["MaxOhn <ohn.m@hotmail.de>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/MaxOhn/rosu-pp-js"
description = "Difficulty and performance calculation for osu!"
keywords = ["osu", "pp", "stars", "performance", "osu!"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rosu-pp = { path = "../rosu-pp" }
wasm-bindgen = "0.2.84"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# opt-level = "s"
