[package]
name = "rosu-pp-js"
version = "0.1.0"
edition = "2021"
description = "TODO: description"
repository = "TODO: repository"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
rosu-pp = { path = "../rosu-pp" }
wasm-bindgen = "0.2.84"
console_error_panic_hook = { version = "0.1.7", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
opt-level = "s"
